### PR TITLE
Documentation for adding AWS_PROFILE

### LINKED ISSUE #94: Allow profiles to be specified
It would be nice if the AWS profile that credentials should be sourced from could be
specified when using `heptio-authenticator-aws`. Of course, this can already be done
by using the `AWS_PROFILE` environment variable. However, adding profiles as an
explicit option would be useful when working with clusters across multiple AWS
accounts and allow seamless switching.

For example, if a `--profile` flag was supported then `kubectl` would not require the
`AWS_PROFILE` environment variable to be modified for each cluster/account. The
appropriate profile could be specified directly in the kubeconfig file, e.g.:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: ${server}
    certificate-authority-data: ${cert}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "mycluster"
        - "-p"
        - "dev"
```

### PR DESCRIPTION
**Pull request by asobrien**
Fixes #94 

Signed-off-by: Anthony O'Brien <anthony@bearonis.com>

### CODE REVIEW

**Comment by christopherhein** [comment]
@asobrien check the issue for feedback… I would say change this and the title to Documentation for adding `AWS_PROFILE`

**Comment by asobrien** [comment]
@christopherhein I've updated the PR so that it just adds documentation that covers specifying credentials and using a `AWS_PROFILE`. The rendered preview is [here](https://github.com/asobrien/authenticator/blob/6586238a19a9683a98b4875a2c9a025bdc6e513f/README.md#specifying-credentials--using-aws-profiles).

**Comment by christopherhein** [comment]
Awesome @asobrien LGTM. @nckturner any chance you can give this a quick review?

**Comment by nckturner** [comment]
@christopherhein Yup taking a look

**Comment by christopherhein** [comment]
The travis issue … looks like a flake? Then again the `goreleaser` version seems out of date by quite a bit…

**Comment by asobrien** [comment]
@christopherhein I added a `--retry` to the curl command when fetching goreleaser. That should cut down on some of the flakiness in the tests.

**Pull request merged**
